const CREATE_USER_TABLE_SQL = `CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      age INTEGER NOT NULL
    )`;

const DROP_USER_TABLE_SQL = "DROP TABLE IF EXISTS users";

export { CREATE_USER_TABLE_SQL, DROP_USER_TABLE_SQL };
